#!/bin/bash
set -o errexit -o nounset -o pipefail
sudo pip install pgxnclient
BREW_LOG=brew.log
PG_DIR=/usr/local/var/postgres/
PG_LOG=$PG_DIR/server.log
HBA_CONF=$PG_DIR/pg_hba.conf
CONF=$PG_DIR/postgresql.conf
TIMEOUT=10

pg_ctl -D $PG_DIR stop -s -m fast -t $TIMEOUT || true
brew update > $BREW_LOG
brew install postgresql >> $BREW_LOG
brew cleanup postgresql >>$BREW_LOG
make clean all install
echo "local    replication     all trust" >> $HBA_CONF
echo "host     replication      all ::1/128  trust" >> $HBA_CONF
echo "max_wal_senders = 1" >> $CONF
echo "wal_level=logical" >> $CONF
echo "max_replication_slots=1" >> $CONF

pg_ctl -D $PG_DIR -l $PG_LOG -w -t $TIMEOUT start/
sleep 5
make test || head -n 10000 /Users/travis/build/posix4e/jsoncdc/regression.diffs; head -n 1000 $PG_LOG
